### ISSUE TITLE
Sudden error after getUpdates

### ISSUE THREAD

**Issue by Alcotana** [mast/telegram-bot-api#41] opened 2016-10-26 10:01 UTC
![screenshot_134](https://cloud.githubusercontent.com/assets/1378484/19721713/2de48c5c-9b7c-11e6-9e90-2246f632f77d.png)

What has happened? I cannot start the server, because of the error.

As far as I remember, I did `npm update telegram-bot-api` just before.

Is this the problem of telegram-bot-api?

**Comment by fluse** [comment] 2016-11-24 15:42
i get this error too.

**Comment by mast** [comment] 2016-11-25 07:41
I checked my test script for getUpdates and it works for me.
Could you please locate place in your code where this happens and share it?

**Comment by fluse** [comment] 2016-11-25 09:16
Hey mast. 

.on('inline.callback.query' will fire .on('message' too

so you get inside on('message an different object where message.chat.id is not under the same dot notation.

**Comment by mast** [comment] 2016-11-25 11:29
> and if you create an error inside message will throw this promise error

not sure I get you here..

Is the following true?

Due to wrong chat.id extraction, you send message to wrong chat (with empty chat_id probably), that's why you receive HTTP 400 back from Telegram servers? It sounds like bug in your code then.

**Comment by mast** [comment] 2020-06-28 18:00
Closing issue as not reproducible

**Closed by mast** 2020-06-28 18:00 UTC
